---
# tasks file for /home/ansible/roles/renzo.mysql
- name: Install epel-release repo
  yum:
    name: "epel-release"
    state: latest
    
- name: install require packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages_list }}"  

- name: start and enable require services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service_list }}"

- name: Mysql secure Installation
  community.mysql.mysql_user:
    name: root
    password: "{{ roots_passwd }}"
  #  login_password: "{{ roots_passwd }}"

- name: copy phpadmin template
  template:
    dest: /etc/httpd/conf.d/phpMyAdmin.conf
    src: phpMyAdmin.conf.j2

- name: add services to the firewall
  firewalld:
    state: enabled
    service: "{{ item }}"
    permanent: yes
    inmediate: yes
  loop: "{{ firewall_services }}"  

- name: restart httpd
  service:
    name: httpd
    state: restarted
